<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symed'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'OpenCloud' => array($vendorDir . '/rs/lb2'),
    'Guzzle' => array($vendorDir . '/guzzle'),
    'Aws' => array($vendorDir . '/aws'),
);
